INSERT INTO usuario (nombre) VALUES ('Pablo');
INSERT INTO usuario (nombre) VALUES ('Carlos');
INSERT INTO usuario (nombre) VALUES ('Carlos');
INSERT INTO usuario (nombre) VALUES ('Carlos');
INSERT INTO usuario (nombre) VALUES ('Pablo');
INSERT INTO usuario (nombre) VALUES ('Pedro');
INSERT INTO usuario (nombre) VALUES ('Paco');
INSERT INTO usuario (nombre) VALUES ('Pablo');
INSERT INTO usuario (nombre, email, apellido, contrasena) VALUES ('Camilo', 'camilo@gmail.com', 'Gonzales', 'camilito12');
INSERT INTO usuario (nombre, email, apellido, contrasena) VALUES ('Pablo', 'pablo@gmail.com', 'Lopez', 'pablito34');
INSERT INTO usuario (nombre, email, apellido, contrasena) VALUES ('Ana', 'ana@gmail.com', 'Garcia', 'anita56');
INSERT INTO usuario (nombre, email, apellido, contrasena) VALUES ('Sofia', 'sofia@gmail.com', 'Rodriguez', 'sofi123');
INSERT INTO usuario (nombre, email, apellido, contrasena) VALUES ('Luis', 'luis@gmail.com', 'Martinez', 'lucho567');
INSERT INTO usuario (nombre, email, apellido, contrasena) VALUES ('Diego', 'diego@gmail.com', 'Gonzales', 'dieguito89');
INSERT INTO usuario (nombre, email, apellido, contrasena) VALUES ('Maria', 'maria@gmail.com', 'Perez', 'marita10');
INSERT INTO usuario (nombre, email, apellido, contrasena) VALUES ('Daniel', 'daniel@gmail.com', 'Sanchez', 'danito23');
INSERT INTO usuario (nombre, email, apellido, contrasena) VALUES ('Camila', 'camila@gmail.com', 'Ramirez', 'camilota45');
INSERT INTO usuario (nombre, email, apellido, contrasena) VALUES ('Pablo', 'pablo2@gmail.com', 'Fernandez', 'pablinho67');
INSERT INTO usuario (nombre, email, apellido, contrasena) VALUES ('Laura', 'laura@gmail.com', 'Gonzales', 'lau234');
INSERT INTO usuario (nombre, email, apellido, contrasena) VALUES ('Gabriel', 'gabriel@gmail.com', 'Lopez', 'gabi123');
INSERT INTO usuario (nombre, email, apellido, contrasena) VALUES ('Carolina', 'carolina@gmail.com', 'Garcia', 'caro567');
INSERT INTO usuario (nombre, email, apellido, contrasena) VALUES ('Sebastian', 'sebastian@gmail.com', 'Rodriguez', 'sebas89');
INSERT INTO usuario (nombre, email, apellido, contrasena) VALUES ('Julia', 'julia@gmail.com', 'Martinez', 'juli123');
INSERT INTO usuario (nombre, email, apellido, contrasena) VALUES ('Andres', 'andres@gmail.com', 'Gonzales', 'andresito10');
INSERT INTO usuario (nombre, email, apellido, contrasena) VALUES ('Valentina', 'valentina@gmail.com', 'Perez', 'vale23');
INSERT INTO usuario (nombre, email, apellido, contrasena) VALUES ('Juan', 'juan@gmail.com', 'Sanchez', 'juancito45');
INSERT INTO usuario (nombre, email, apellido, contrasena) VALUES ('Camila', 'camila2@gmail.com', 'Ramirez', 'camilin678');
INSERT INTO usuario (nombre, email, apellido, contrasena) VALUES ('Pablo', 'pablo3@gmail.com', 'Fernandez', 'pablin345');

